spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:dm://192.168.88.131:5236/SYSDBA
    username: SYSDBA
    password: Dameng@123
    driver-class-name: dm.jdbc.driver.DmDriver

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    druid:
      filters: stat,wall,log4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB


  thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 映射文件位置
  type-aliases-package: com.emergency.drill.entity  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动转换
    cache-enabled: true  # 开启二级缓存
    lazy-loading-enabled: true  # 开启延迟加载
    aggressive-lazy-loading: false  # 禁用积极延迟加载

# 日志配置
logging:
  level:
    com.emergency.drill.mapper: DEBUG  # 打印SQL日志
    root: INFO  # 根日志级别

# 服务器配置
server:
  port:  8080  # 服务器端口
  servlet:
    context-path: /emergency-drill  # 项目上下文路径
  tomcat:
    max-threads: 200  # 最大线程数
    max-connections: 8192  # 最大连接数


